name: SetSync
options:
  bundleIdPrefix: com.domingoruizb
  deploymentTarget:
    iOS: "17.0"
targets:
  SetSync:
    type: application
    platform: iOS
    sources:
      - App/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.domingoruizb.setsync
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
